---
title: "xgb NLP Modeling"
author: "Keenan Smith"
---

```{r}
#| output: false
#| label: Reading in initial Libraries
here::i_am("content/modeling/bigram_nlp_modeling_xgb_tfidf.qmd")
library(tidymodels)

library(parallel)
all_cores <- parallel::detectCores(logical = FALSE)
cl <- parallel::makePSOCKcluster(all_cores)
doParallel::registerDoParallel(cl)

sparse_bp <- hardhat::default_recipe_blueprint(composition = "dgCMatrix")

docid_to_bias <- function(df) {
  df |>
    tidytable::separate_wider_delim(doc_id, delim = "_", names = c("short_source", "pull_index", "source_bias"), cols_remove = TRUE) |>
    tidytable::select(-short_source, -pull_index)
}
```

```{r}
bigram_tfidf <- tidytable::fread(here::here("data", "model_data", "tfidf_bigram_df_4k.csv.gz"))

rownames(bigram_tfidf) <- bigram_tfidf$doc_id
```

# Getting Classification out of Doc ID

```{r}
bigram_tfidf <- docid_to_bias(bigram_tfidf)
```

# Data Split

```{r}
set.seed(2023)
tfidf_split <- initial_split(bigram_tfidf, strata = source_bias)

bigram_train <- training(tfidf_split)
bigram_test <- testing(tfidf_split)
bigram_folds <- vfold_cv(bigram_train)
```

# Engine

```{r}
library(xgboost)

tune_spec <- boost_tree(
  trees = 1000,
  tree_depth = tune(), 
  min_n = tune(),
  loss_reduction = tune(),
  learn_rate = tune()) |>
  set_mode("classification") |>
  set_engine("xgboost")
```

# Tune Grid

```{r}
xgboost_params <- 
  dials::parameters(
    min_n(),
    tree_depth(),
    learn_rate(),
    loss_reduction()
  )

xgb_grid <- 
  dials::grid_max_entropy(
    xgboost_params, 
    size = 10
  )
```

# Recipes

```{r}
text_rec <- recipe(source_bias ~ ., data = bigram_train)
```

# Workflows

```{r}
tune_wf <- workflow() |>
  add_recipe(text_rec, blueprint = sparse_bp) |>
  add_model(tune_spec)
```

# Metric Set

```{r}
class_metrics <- metric_set(sens, spec, recall, precision, f_meas, accuracy, roc_auc, pr_auc)
```

# Hyperparameter Tuning

```{r}
tune_rs <- tune_grid(
  tune_wf,
  bigram_folds,
  grid = xgb_grid,
  metrics = class_metrics,
)

readr::write_rds(tune_rs, "model_data/tune_results_xgb_tfidf.rds")
```

# Hyperparameter Metrics

```{r}
xgb_rs_metrics <- collect_metrics(tune_rs)
tidytable::fwrite(xgb_rs_metrics, here::here("content", "modeling", "model_results", "xgb_rs_metrics_tfidf_bigrams_4k.csv"))

show_best(tune_rs)
```

## Metric vs. Lambda

```{r}
tune_rs |>
  collect_metrics() |>
  filter(.metric == "roc_auc") |>
  select(mean, min_n:loss_reduction) |>
  pivot_longer(min_n:loss_reduction,
               values_to = "value",
               names_to = "parameter"
  ) |>
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "AUC")

ggsave("plots/cv_metrics_xgb_tfidf.png")
```

# Selecting Best ROC-AUC to tune Model

```{r}
chosen_auc <- tune_rs |>
  select_best(metric = "roc_auc")

final_xgb <- finalize_workflow(tune_wf, chosen_auc)
```

# Fitting Model on Training Data

```{r}
fitted_xgb <- fit(final_xgb, bigram_train)
```

# Variable Importance Examination

## Variable Importance Plot

```{r}
library(vip)

vip_xgboost <- fitted_xgboost |>
  extract_fit_parsnip() |>
  vi()

vip_xgboost |>
  slice_head(n = 20) |>
  ggplot(aes(x = Importance, y = Variable)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = NULL)

ggsave("plots/variable_importance_plot_xgb_tfidf.png")
```

```{r}
last_fit_xgb <- last_fit(final_xgb, tfidf_split)

xgb_metric <- last_fit_xgb |>
  collect_predictions() |>
  class_metrics(source_bias, estimate = .pred_class, `.pred_left-wing`)

tidytable::fwrite(xgb_metric, "model_results/xgb_test_metrics_tfidf.csv")

last_fit_xgb |>
  collect_predictions() |>
  roc_curve(source_bias, `.pred_left-wing`) |>
  autoplot()

ggsave("plots/roc_curve_xgb_tfidf.png")

last_fit_xgb |>
  collect_predictions() |>
  conf_mat(source_bias, .pred_class) |>
  autoplot(type = "heatmap")

ggsave("plots/confusion_matrix_xgb_tfidf.png")
```

