---
title: "Link Preparation"
author: "Keenan Smith"
---

```{r}
here::i_am("content/webscrape/link_preparation.qmd")
library(here)
library(DBI)
library(duckdb)
library(tidytable)
```

# Connecting to DuckDB

```{r}
pol_sent_db <- dbConnect(duckdb::duckdb(), dbdir = here("data","political-sentiment.duckdb"))
```

# Loading Lazy DB for dbplyr

```{r}
sitemaps <- dplyr::tbl(pol_sent_db, "sitemap_data")
linkchecker <- dplyr::tbl(pol_sent_db, "linkchecker_data")
source_table <- dplyr::tbl(pol_sent_db, "source_table")
```

# Function Block for Scraping

```{r}
# Function Block for Obtaining Viable Links
sitemap_viable_links <- function(df,
                                 short.source = NULL,
                                 art.source = NULL,
                                 url.filter,
                                 exclude = FALSE) {
  # Defining OR statement here since DBplyr doesn't like it
  url.filter <- stringr::str_c(stringr::regex("\\w/"),
    url.filter,
    stringr::regex("/\\w"),
    collapse = "|"
  )
  # Checking if art.source exists
  if (is.null(art.source)) {
    # Checking if strings are inclusion or exclusion
    if (exclude == FALSE) {
      # Inclusion
      df |>
        dplyr::left_join(source_table, by = source_table$art_source) |>
        dplyr::filter(
          short_source == short.source,
          stringr::str_detect(url, url.filter),
          stringr::str_detect(url, "page=", negate = TRUE)
        ) |>
        dplyr::collect() |>
        tidytable::distinct(url, .keep_all = TRUE)
    } else {
      # Exclusion
      df |>
        dplyr::left_join(source_table, by = source_table$art_source) |>
        dplyr::filter(
          short_source == short.source,
          stringr::str_detect(url, url.filter, negate = TRUE)
        ) |>
        dplyr::collect() |>
        tidytable::distinct(url, .keep_all = TRUE)
    }
    # If short.source is not used
  } else if (is.null(short.source)) {
    df |>
      dplyr::filter(
        art_source == art.source,
        stringr::str_detect(url, url.filter),
        stringr::str_detect(url, "page=", negate = TRUE)
      ) |>
      dplyr::collect() |>
      tidytable::distinct(url, .keep_all = TRUE)
  }
}

initial_helper <- function(.df, short.source = NULL, art.source = NULL) {
  if (is.null(art.source)) {
    .df |>
      dplyr::left_join(source_table, by = source_table$art_source) |>
      dplyr::filter(short_source == short.source) |>
      dplyr::collect()
  } else if (is.null(short.source)) {
    .df |>
      dplyr::filter(art_source == art.source) |>
      dplyr::collect()
  }
}

initial_look <- function(.df, short.source) {
  temp <- initial_helper(.df, short.source)
  urls <- tidytable::map_df(.x = temp$url, .f = xml2::url_parse)
  return(urls)
}

path_examination <- function(.df) {
  .df |>
    tidytable::separate_wider_delim(path, "/") |>
    tidytable::group_by(path2) |>
    tidytable::count(sort = T)
}
```

# Building SQL for Functions

# Printing Source Table for Reference

```{r}
source_table
```

# Link Exploration

```{r}
initial_look(sitemaps, "wilson") |>
  path_examination()

wilson_include <- c("article", "blog-post")

filtered_wilson <- sitemap_viable_links(sitemaps, short.source = "wilson", url.filter = wilson_include)
```

```{r}
initial_look(sitemaps, "demos") |>
  path_examination()

demos_include <- c("blog", "press-release")

filtered_demos <- sitemap_viable_links(sitemaps, short.source = "demos", url.filter = demos_include)
```

```{r}
initial_look(sitemaps, "iiss") |>
  path_examination()

iiss_include <- c("online-analysis")

filtered_iiss <- sitemap_viable_links(sitemaps, short.source = "iiss", url.filter = iiss_include)
```


```{r}
initial_look(sitemaps, "third") |>
  path_examination()

third_include <- c("memo", "report", "press", "blog")

filtered_third <- sitemap_viable_links(sitemaps, short.source = "third", url.filter = third_include)
```


```{r}
initial_look(sitemaps, "berg") |>
  path_examination()

berg_include <- c("news", "ideas")

filtered_berg <- sitemap_viable_links(sitemaps, short.source = "berg", url.filter = berg_include)
```


```{r}
initial_look(sitemaps, "fab") |>
  path_examination()

fab_filter <- initial_look(sitemaps, "fab") |>
  path_examination() |>
  tidytable::filter(n > 1)

fab_exclude <- fab_filter[[1]]
rm(fab_filter)

filtered_fab <- sitemap_viable_links(sitemaps, short.source = "fab", url.filter = fab_exclude, exclude = TRUE)
```

```{r}
initial_look(sitemaps, "cfr") |>
  path_examination()

cfr_include <- c("article", "in-brief")

filtered_cfr <- sitemap_viable_links(sitemaps, short.source = "cfr", url.filter = cfr_include)
```

# Disconnect

```{r}
#| label: Disconnect Block
dbDisconnect(pol_sent_db, shutdown = TRUE)
```