---
title: "Function Test and Realignment"
author: "Keenan Smith"
format: html
---

# Link Block

```{r}
art_link <- hyperlink
```


# Title Block

```{r}

title_pull <- function(.html, css.tag) {
  .html |>
    rvest::html_elements(css = css.tag) |>
    rvest::html_text2()
}

# Jacobin
art_title <-
  temp |>
  rvest::html_elements(css = ".po-hr-cn__title") |>
  rvest::html_text2()

# Heritage Com
art_title <-
    temp |>
    rvest::html_elements(css = ".commentary__headline") |>
    rvest::html_text2()

# Heritage Rep
art_title <-
    temp |>
    rvest::html_elements(css = ".headline") |>
    rvest::html_text2()

# Brookings
  art_title <-
    temp |>
    rvest::html_elements(css = ".page-content .report-title") |>
    rvest::html_text2()
```


# Author Block

```{r}
# Jacobin
art_author <-
  temp |>
  rvest::html_elements(css = ".po-hr-cn__author-link") |>
  rvest::html_text2()
if (length(art_author) > 1) {
  art_author <- paste(art_author, collapse = ", ")
} else if (length(art_author) == 1) {
  art_author <- art_author
} else {
  art_author <- "Jacobin"
}

# Heritage Com
authors <- c(".author-card__name", "author-card__multi-name")
  art_author_1 <-
    temp |>
    rvest::html_nodes(".author-card__name") |>
    rvest::html_text2()
  art_author_2 <-
    temp |>
    rvest::html_nodes(".author-card__multi-name") |>
    rvest::html_text2()
  art_author <- c(art_author_1, art_author_2)
  if (length(art_author) > 1) {
    art_author <- paste(art_author, collapse = ", ")
  } else if (length(art_author) == 1) {
    art_author <- art_author
  } else {
    art_author <- "Heritage Foundation"
  }
# Heritage Rep  
art_author_1 <-
  temp |>
  rvest::html_nodes(".contributor-card") |>
  rvest::html_text2() |>
  str_remove("Authors: ")
art_author_2 <-
  temp |>
  rvest::html_nodes(".expert-card__expert-name") |>
  rvest::html_text2()
art_author <- c(art_author_1, art_author_2)
if (length(art_author) > 1) {
  art_author <- paste(art_author, collapse = ", ")
} else if (length(art_author) == 1) {
  art_author <- art_author
} else {
  art_author <- "Heritage Foundation"
}

# Brookings
  art_author <-
    temp |>
    rvest::html_elements(css = ".names") |>
    rvest::html_text2()
  if (length(art_author) > 1) {
    art_author <- paste(art_author, collapse = ", ")
  } else if (length(art_author) == 1) {
    art_author <- art_author
  } else {
    art_author <- "Brookings Institute"
  }
```

# Topic Block

```{r}
# Jacobin
  art_topic <-
    temp |>
    rvest::html_elements(css = ".po-hr-fl__taxonomy") |>
    rvest::html_text2()
  if (length(art_topic) > 1) {
    art_topic <- paste(art_topic, collapse = ", ")
  } else if (length(art_topic) == 1) {
    art_topic <- art_topic
  } else {
    art_topic <- NA
  }
# Heritage Com
temp_topic <- hyperlink |>
    stringr::str_split("/") |>
    as_vector()
  art_topic <- temp_topic[[4]]
  
# Heritage Rep
temp_topic <- hyperlink |>
    stringr::str_split("/") |>
    as_vector()
  art_topic <- temp_topic[[4]]
  
# Brookings
  art_topic <-
    temp |>
    rvest::html_elements(css = ".series-header") |>
    rvest::html_text2()
  if (length(art_topic) > 1) {
    art_topic <- art_topic[[2]]
  } else if (length(art_topic) == 1) {
    art_topic <- art_topic
  } else {
    temp_topic <- hyperlink |>
      stringr::str_split("/") |>
      as_vector()
    art_topic <- temp_topic[[5]]
  }
```

# Date Block

```{r}
# Jacobin
art_date <-
    temp |>
    rvest::html_elements(css = ".po-hr-fl__date") |>
    rvest::html_text2() |>
    stringr::str_replace("\\.", "/") |>
    lubridate::mdy()

# Heritage Com
date_formats <- "[:alpha:]+ [:graph:]+ [:digit:]+"
art_date <-
    temp |>
    rvest::html_elements(css = ".article-general-info") |>
    rvest::html_text2() |>
    stringr::str_extract(date_formats) |>
    lubridate::mdy()

# Heritage Rep
  art_date <-
    temp |>
    rvest::html_elements(css = ".article-general-info") |>
    rvest::html_text2() |>
    stringr::str_extract(date_formats) |>
    lubridate::mdy()

# Brookings
art_date <-
    temp |>
    rvest::html_elements("time[content]") |>
    rvest::html_text2() |>
    lubridate::mdy()
```

# Text Block

```{r}

text_pull <- function(.html, css.tag) {
  .html |>
    rvest::html_element(css = css.tag) |>
    rvest::html_nodes("p") |>
    rvest::html_text2() |>
    tidytable::as_tidytable() |>
    tidytable::rename(text = value)
}

# Jacobin
text_data <-
    temp |>
    rvest::html_element(css = "#post-content") |>
    rvest::html_nodes("p") |>
    rvest::html_text2() |>
    dplyr::as_tibble() |>
    dplyr::rename(text = value)

# Heritage Com
text_data <-
    temp |>
    rvest::html_nodes(".article__body-copy") |>
    rvest::html_nodes("p") |>
    rvest::html_text2() |>
    dplyr::as_tibble() |>
    dplyr::rename(text = value)

# Heritage Rep
text_data <-
    temp |>
    rvest::html_nodes(".article__body-copy") |>
    rvest::html_nodes("p") |>
    rvest::html_text2() |>
    dplyr::as_tibble() |>
    dplyr::rename(text = value)

# Brookings Data
text_data <-
    temp |>
    rvest::html_element(css = ".post-body") |>
    rvest::html_nodes("p") |>
    rvest::html_text2() |>
    dplyr::as_tibble() |>
    dplyr::rename(text = value)
```

# Combo Block

```{r}

combination_tidytable <- function(art.title, art.author, art.date, art.topic,
                                  art.link, art.text, art.source) {
  
  tidytable::tidytable(art_title = art.title, art_author = art.author,
                       art_date = art.date, art_topic = art.topic, 
                       art_link = art.link, art_text = art.text,
                       art_source = art.source)
}

# Jacobin
temp |>
  dplyr::mutate(
      art_title = art_title,
      art_author = art_author,
      art_date = art_date,
      art_topic = art_topic,
      art_link = art_link,
      art_source = "Jacobin")

# Heritage Com
temp |>    
  dplyr::mutate(
      art_title = art_title,
      art_author = art_author,
      art_date = art_date,
      art_topic = art_topic,
      art_link = art_link,
      art_source = "Heritage Commentary"
    )

# Heritage Rep
temp |>
  dplyr::mutate(
      art_title = art_title,
      art_author = art_author,
      art_date = art_date,
      art_topic = art_topic,
      art_link = art_link,
      art_source = "Heritage Report"
    )

# Brookings
temp |>
  dplyr::mutate(
      art_title = art_title,
      art_author = art_author,
      art_date = art_date,
      art_topic = art_topic,
      art_link = art_link,
      art_source = "Brookings Institute"
    )
```

# Old Function Staging

